services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: procurement_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Redis for caching and job queue
  redis:
    image: redis:7-alpine
    container_name: procurement_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: procurement_api
    depends_on:
      postgres:
        condition: service_healthy # <-- THIS IS THE FIX
      redis:
        condition: service_started
      selenium-hub:
        condition: service_started
    env_file: .env # Use the .env file
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - ./logs:/app/logs
    command: python main.py

  # Selenium Grid Hub
  selenium-hub:
    image: selenium/hub:4.15.0
    container_name: selenium_hub
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"

  # Selenium Chrome Node
  selenium-chrome:
    image: selenium/node-chrome:4.15.0
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
    volumes:
      - /dev/shm:/dev/shm
    deploy:
      replicas: 2

  # Celery worker for background jobs
  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: procurement_celery
    depends_on:
      postgres:
        condition: service_healthy # <-- THIS IS THE FIX
      redis:
        condition: service_started
      selenium-hub:
        condition: service_started
    env_file: .env # Use the .env file
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - ./logs:/app/logs
    command: celery -A tasks worker --loglevel=info

  # Celery beat for scheduled tasks
  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: procurement_beat
    depends_on:
      postgres:
        condition: service_healthy # <-- THIS IS THE FIX
      redis:
        condition: service_started
    env_file: .env # Use the .env file
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
    command: celery -A tasks beat --loglevel=info

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: procurement_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: procurement_network